# Generated by Django 2.2.4 on 2019-10-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformclass',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationformclass',
            name='order_id',
            field=models.CharField(default='1d83l7', max_length=10),
        ),
    ]
